#Marlon


import turtle
import random
CanJump = True
Area=turtle.Screen()
bob=turtle.Turtle()
MyX=bob.xcor()
MyY=bob.ycor()
l=80
m=65
n=9
x=82
windcol=212
windcol2=247
windcol3=250
pixelsize=15
bob.penup()
bob.goto(-200,200)
bob.pendown()
bob.speed()
bob.color(156, 22, 12)

#sky
turtle.tracer(0, 0)
for i in range(1):
    bob.color(86,230,232)
    for i in range (30):
      bob.begin_fill()
      bob.color(x,230,232)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    bob.goto(-200,200-pixelsize)
    bob.color(106,230,232)
    for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    bob.goto(-200,200-pixelsize*2)
    bob.color(116,230,232)
    for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    bob.goto(-200,200-pixelsize*3)
    bob.color(126,230,232)
    for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    bob.penup()
    bob.goto(-200,200-pixelsize*4)
    bob.pendown()
    bob.color(136,230,232)
    for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    bob.penup()
    bob.goto(-200,200-pixelsize*5)
    bob.pendown()
    bob.color(146,230,232)
    for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    bob.penup()
    bob.goto(-200,200-pixelsize*6)
    bob.pendown()
    bob.color(156,230,232)
    for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    bob.penup()
    bob.goto(-200,200-pixelsize*7)
    bob.pendown()
    bob.color(166,230,232)
    for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    bob.penup()
    bob.goto(-200,200-pixelsize*8)
    bob.pendown()
    bob.color(176,230,232)
    for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    bob.penup()
    bob.goto(-200,200-pixelsize*9)
    bob.pendown()
    bob.color(186,230,232)
    for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    bob.penup()
    bob.goto(-200,200-pixelsize*10)
    bob.pendown()
    bob.color(196,230,232)
    for i in range (10):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    for i in range (10):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    for i in range (10):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    bob.penup() 
    bob.goto(-200,200-pixelsize*11)
    bob.pendown()
    bob.color(206,230,232)
    for i in range (10):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    for i in range (10):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    for i in range (10):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    bob.penup() 
    bob.goto(-200,200-pixelsize*12)
    bob.pendown()
    bob.color(216,230,232)
    for i in range (10):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    for i in range (10):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    for i in range (10):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    bob.penup() 
    bob.goto(-200,200-pixelsize*13)
    bob.pendown()
    bob.color(226,230,232)
    for i in range (10):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    for i in range (20):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    bob.penup() 
    bob.goto(-200,200-pixelsize*14)
    bob.pendown()
    bob.color(236,230,232)
    for i in range (10):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    for i in range (10):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    for i in range (5):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    for i in range (5):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    bob.penup() 
    bob.goto(-200,200-pixelsize*15)
    bob.color(246,230,232)
    for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    bob.goto(-200,200-pixelsize*16)
    bob.color(255,230,232)
    for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    bob.goto(-200,200-pixelsize*17)
    for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
    bob.goto(-200,200-pixelsize*18)
    for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
#grass
for i in range (1):
  bob.goto(-200,200-pixelsize*19)
  bob.color(x, 200, 72)
  for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
  bob.goto(-200,200-pixelsize*20)
  bob.color(x,195, 72)
  for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
  bob.goto(-200,200-pixelsize*21)
  bob.color(x,190, 72)
  for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
  bob.goto(-200,200-pixelsize*22)
  bob.color(x,185, 72)
  for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
  bob.goto(-200,200-pixelsize*23)
  bob.color(x,180, 72)
  for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
  bob.goto(-200,200-pixelsize*24)
  bob.color(x,175, 72)
  for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
  bob.goto(-200,200-pixelsize*25)
#house
for i in range(1):
  bob.penup()
  bob.goto(-100,-pixelsize*-2)
  bob.color(156, 22, 12)
  bob.left(90)
  bob.forward(100)
  bob.right(90)
  bob.forward(300)
  bob.right(90)
  bob.forward(200)
  bob.right(90)
  bob.forward(300)  
  bob.right(90)
  bob.forward(100)
  bob.penup()
  bob.goto(-100,0)
  bob.right(90)
  for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
  bob.goto(-100,pixelsize*-1)
  bob.color(155, 22, 12)
  for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
  bob.goto(-100,pixelsize*-2)
  bob.color(160, 22, 12)
  for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
  bob.goto(-100,pixelsize*-3)
  bob.color(165, 22, 12)
  for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
  bob.goto(-100,pixelsize*-4)
  bob.color(170,22,12)
  for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
  bob.goto(-100,pixelsize*-5)
  bob.color(175,22,12)
  for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
  bob.goto(-100,pixelsize*-6)
  bob.color(180,22,12)
  for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
  bob.goto(-100,pixelsize*-7)
  bob.color(185,22,12)
  for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
  bob.goto(-100,pixelsize*-8)
  bob.color(190,22,12)
  for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
  bob.goto(-100,pixelsize*-8.5)
  bob.color(195,22,12)
  for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
  bob.goto(-100,pixelsize*-9)
  bob.color(200,22,12)
  for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
  bob.goto(-100,pixelsize*-9.5)
  bob.color(205, 22, 12)
  for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
  bob.goto(-100,pixelsize*-10)
  bob.color(210, 22, 12)
  for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
  bob.goto(-100,pixelsize*-10.5)
  bob.color(215, 22, 12)
  for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
  bob.goto(-100,pixelsize*-11)
  bob.color(220,22,12)
  for i in range (30):
      bob.begin_fill()
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.right(90)
      bob.forward(pixelsize)
      bob.end_fill()
  bob.goto(-100,pixelsize*-11.5)
bob.left(90)
bob.penup()
bob.forward(154)
bob.right(90)
bob.pendown()
#roof
for i in range(1):
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(24, 25, 26)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-100,pixelsize)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(29, 30, 31)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-98,pixelsize*0.25)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(34, 35, 36)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-96,pixelsize*0.5)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(39, 40, 41)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-94,pixelsize*0.75)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(44, 45, 46)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-92,pixelsize*1)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(49, 50, 51)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-90,pixelsize*1.25)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(54, 55, 56)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-88,pixelsize*1.5)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(59, 60, 61)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-86,pixelsize*1.75)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(64, 65, 66)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-84,pixelsize*2)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(69, 70, 71)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-82,pixelsize*2.25)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(74, 75, 76)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-80,pixelsize*2.5)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(79, 80, 81)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-78,pixelsize*2.75)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(84, 85, 86)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-76,pixelsize*3)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(89, 90, 94)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-74,pixelsize*3.25)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(94, 95, 99)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-72,pixelsize*3.5)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(24, 25, 26)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-70,pixelsize*3.75)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(29, 30, 31)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-68,pixelsize*4)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(34, 35, 36)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-66,pixelsize*4.25)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(39, 40, 41)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-64,pixelsize*4.5)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(44, 45, 46)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-62,pixelsize*4.75)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(49, 50, 51)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-60,pixelsize*5)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(54, 55, 56)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-58,pixelsize*5.25)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(59, 60, 61)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-56,pixelsize*5.5)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(64, 65, 66)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-54,pixelsize*5.75)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(69, 70, 71)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-52,pixelsize*6)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(74, 75, 76)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-50,pixelsize*6.25)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(79, 80, 81)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-48,pixelsize*6.5)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(84, 85, 86)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-46,pixelsize*6.75)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(89,90,91)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-44,pixelsize*7)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(94, 95,96)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-42,pixelsize*7.25)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(99,100, 101)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-40,pixelsize*7.5)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(24, 25, 26)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-38,pixelsize*7.75)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(29, 30, 31)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-36,pixelsize*8)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(34, 35, 36)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-34,pixelsize*8.25)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(39, 40, 41)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-32,pixelsize*8.5)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(44, 45, 46)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-30,pixelsize*8.75)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(49, 50, 54)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-28,pixelsize*9)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(54, 55, 56)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-26,pixelsize*9.25)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(59, 60, 61)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-24,pixelsize*9.5)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(64, 65, 66)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-22,pixelsize*9.75)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(69, 70, 71)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-20,pixelsize*10)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(74, 75, 76)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-18,pixelsize*10.25)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(79, 80, 81)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-16,pixelsize*10.5)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(84, 85, 86)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-14,pixelsize*10.75)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(89, 90, 94)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-12,pixelsize*11)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(94, 95, 96)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-10,pixelsize*11.25)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(99, 100, 101)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-8,pixelsize*11.5)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(24, 25, 26)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-6,pixelsize*11.75)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(29, 30, 31)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-4,pixelsize*12)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(34, 35, 36)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(-2,pixelsize*12.25)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(39, 40, 41)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,pixelsize*12.5)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(44, 45, 46)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(2,pixelsize*12.75)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(59, 60, 61)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(4,pixelsize*13)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(64, 65, 66)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(6,pixelsize*13.25)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(69, 70, 71)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(8,pixelsize*13.5)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(74, 75, 76)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(10,pixelsize*13.75)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(79, 80, 81)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(12,pixelsize*14)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(84, 85, 86)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(14,pixelsize*14.25)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(89, 90, 91)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(16,pixelsize*14.5)
  for i in range (100):
    bob.pendown()
    bob.begin_fill()
    bob.color(94, 95, 96)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
bob.penup()
bob.goto(0,-178)
bob.pendown()
#door
for i in range(1):
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l, m, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-178)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+2, m+2, n+2)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-175)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+4, m+4, n+4)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-172)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+6, m+6, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-169)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+8, m+8, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-166)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+10, m+10, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-163)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+12, m+12, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-160)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+14, m+14, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-157)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+16, m+16, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-154)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+18, m+18, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-151)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+20, m+20, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-148)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+22, m+22, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-145)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+24, m+24, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-142)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+26, m+26, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-139)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+28, m+28, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-136)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+30, m+30, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-133)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+32, m+32, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-130)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+34, m+34, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-127)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+36, m+36, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-124)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+38, m+38, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-121)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+40, m+40, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-118)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+42, m+42, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-115)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+44, m+44, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-112)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+46, m+46, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-109)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+48, m+48, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-106)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+50, m+50, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-103)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+52, m+52, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-100)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+54, m+54, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-97)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+56, m+56, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-94)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+58, m+58, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-91)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+60, m+60, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-88)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+62, m+62, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-85)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+64, m+64, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-82)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+66, m+66, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-79)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+68, m+68, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-76)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+70, m+70, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-73)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+72, m+72, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-70)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+74, m+74, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-68)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+76, m+76, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-65)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+78, m+78, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-62)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+80, m+80, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-59)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+82, m+82, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-56)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+84, m+84, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-53)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+86, m+86, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-50)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+88, m+88, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-47)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+90, m+90, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-44)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+92, m+92, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-41)
  for i in range (20):
    bob.pendown()
    bob.begin_fill()
    bob.color(l+94, m+94, n)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.right(90)
    bob.forward(pixelsize/5)
    bob.end_fill()
    bob.penup()
  bob.goto(0,-38)
#window
bob.goto(90,-38)
for i in range(1):
  bob.color(windcol, windcol2, windcol3)
  for i in range (20):
      bob.pendown()
      bob.begin_fill()
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.end_fill()
      bob.penup()
  bob.goto(90,-41)
  bob.color(windcol-2, windcol2-2, windcol3)
  for i in range (20):
      bob.pendown()
      bob.begin_fill()
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.end_fill()
      bob.penup()
  bob.goto(90,-44)
  bob.color(windcol-4, windcol2-4, windcol3)
  for i in range (20):
      bob.pendown()
      bob.begin_fill()
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.end_fill()
      bob.penup()
  bob.goto(90,-47)
  bob.color(windcol-6, windcol2-6, windcol3)
  for i in range (20):
      bob.pendown()
      bob.begin_fill()
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.end_fill()
      bob.penup()
  bob.goto(90,-50)
  bob.color(windcol-8, windcol2-8, windcol3)
  for i in range (20):
      bob.pendown()
      bob.begin_fill()
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.end_fill()
      bob.penup()
  bob.goto(90,-53)
  bob.color(windcol-10, windcol2-10, windcol3)
  for i in range (20):
      bob.pendown()
      bob.begin_fill()
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.end_fill()
      bob.penup()
  bob.goto(90,-56)
  bob.color(windcol-12, windcol2-12, windcol3)
  for i in range (20):
      bob.pendown()
      bob.begin_fill()
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.end_fill()
      bob.penup()
  bob.goto(90,-59)
  bob.color(windcol-14, windcol2-14, windcol3)
  for i in range (20):
      bob.pendown()
      bob.begin_fill()
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.end_fill()
      bob.penup()
  bob.goto(90,-62)
  bob.color(windcol-14, windcol2-14, windcol3)
  for i in range (20):
      bob.pendown()
      bob.begin_fill()
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.end_fill()
      bob.penup()
  bob.goto(90,-65)
  bob.color(windcol-14, windcol2-14, windcol3)
  for i in range (20):
      bob.pendown()
      bob.begin_fill()
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.end_fill()
      bob.penup()
  bob.goto(90,-68)
  bob.color(windcol-16, windcol2-16, windcol3)
  for i in range (20):
      bob.pendown()
      bob.begin_fill()
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.end_fill()
      bob.penup()
  bob.goto(90,-71)
  bob.color(windcol-16, windcol2-16, windcol3)
  for i in range (20):
      bob.pendown()
      bob.begin_fill()
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.end_fill()
      bob.penup()
  bob.goto(90,-74)
  bob.color(windcol-18, windcol2-18, windcol3)
  for i in range (20):
      bob.pendown()
      bob.begin_fill()
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.end_fill()
      bob.penup()
  bob.goto(90,-77)
  bob.color(windcol-20, windcol2-20, windcol3)
  for i in range (20):
      bob.pendown()
      bob.begin_fill()
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.end_fill()
      bob.penup()
  bob.goto(90,-80)
  bob.color(windcol-22, windcol2-22, windcol3)
  for i in range (20):
      bob.pendown()
      bob.begin_fill()
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.end_fill()
      bob.penup()
  bob.goto(90,-83)
  bob.color(windcol-24, windcol2-24, windcol3)
  for i in range (20):
      bob.pendown()
      bob.begin_fill()
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.end_fill()
      bob.penup()
  bob.goto(90,-86)
  bob.color(windcol-26, windcol2-26, windcol3)
  for i in range (20):
      bob.pendown()
      bob.begin_fill()
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.end_fill()
      bob.penup()
  bob.goto(90,-89)
  bob.color(windcol-28, windcol2-28, windcol3)
  for i in range (20):
      bob.pendown()
      bob.begin_fill()
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.end_fill()
      bob.penup()
  bob.goto(90,-92)
  bob.color(windcol-30, windcol2-30, windcol3)
  for i in range (20):
      bob.pendown()
      bob.begin_fill()
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.end_fill()
      bob.penup()
  bob.goto(90,-95)
  bob.color(windcol-32, windcol2-32, windcol3)
  for i in range (20):
      bob.pendown()
      bob.begin_fill()
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.right(90)
      bob.forward(pixelsize/5)
      bob.end_fill()
  bob.goto(90,-98)
for i in range(4):
  bob.color(0,0,0)
  bob.forward(0)
  bob.left(90)

bob.hideturtle()
bob.penup()
bob.setpos(-115,-150)
bob.color("black")
bob.write("Marlon - Year 9", font=("Arial", 26, "normal"))
 
bob.update()
