#Haroon in Year 10
import turtle 
bob = turtle.Turtle()

#for testing purposes: speed
if 1 == 1:
  bob.speed(0)

#for testing purposes: more speed
if 1 == 0:
  bob.tracer(0,0)


bob.penup()
bob.goto(-150,150)
bob.pendown()
bob.forward(150)
bob.right(90)
bob.forward(225)
bob.right(90)
bob.forward(150)
bob.right(90)
bob.forward(225)
bob.penup()
bob.goto(-100,-65)
bob.pendown()
bob.forward(10)
bob.right(90)
bob.forward(40)
bob.right(90)
bob.forward(10)
bob.right(90)
bob.forward(40)
bob.seth(90)
bob.penup()
bob.forward(2)
bob.write(" ©Nintendo", font= ("courier new",5,"normal"))
bob.penup()
bob.goto(-45,-60)
bob.left(45)


#sound bottom right
bob.pendown()
bob.forward(25)
bob.penup()
bob.goto(-45,-60)
bob.right(90)
bob.forward(5)
bob.left(90)
bob.pendown()
bob.forward(25)
bob.penup()
bob.goto(-45,-60)
bob.right(90)
bob.forward(5)
bob.left(90)
bob.right(90)
bob.penup()
bob.forward(5)
bob.left(90)
bob.pendown()
bob.forward(25)
bob.penup()
bob.goto(-45,-60)
bob.right(90)
bob.forward(15)
bob.left(90)
bob.pendown()
bob.forward(25)
bob.penup()
bob.goto(-45,-60)
bob.right(90)
bob.forward(20)
bob.left(90)
bob.pendown()
bob.forward(25)
bob.penup()
bob.goto(-45,-60)
bob.right(90)
bob.forward(25)
bob.left(90)
bob.pendown()
bob.forward(25)
bob.penup()


#buttons for start and select
bob.goto(-115,-20)
bob.right(90)
bob.pendown()
bob.forward(20)
bob.penup()
bob.back(20)
bob.color("blue")
bob.write(" SELECT", font= ("courier new",5,"normal"))
bob.color("black")
bob.penup()
bob.goto(-85,-20)
bob.pendown()
bob.forward(20)
bob.penup()
bob.back(20)
bob.color("blue")
bob.write(" START", font= ("courier new",5,"normal"))
bob.color("black")

#gamepad
bob.penup()
bob.goto(-125,-5)
bob.seth(90)
bob.begin_fill()
bob.pendown()
bob.forward(15)
bob.left(90)
bob.forward(15)
bob.right(90)
bob.forward(15)
bob.right(90)
bob.forward(15)
bob.left(90)
bob.forward(15)
bob.right(90)
bob.forward(15)
bob.right(90)
bob.forward(15)
bob.left(90)
bob.forward(15)
bob.right(90)
bob.forward(15)
bob.right(90) 
bob.forward(15)
bob.left(90)
bob.forward(15)
bob.right(90)
bob.forward(15)
bob.end_fill()

#buttons for AB/ game main game buttons
bob.seth(90)
bob.penup()
bob.goto(-50,10)
bob.begin_fill()
bob.fillcolor(164, 24, 62)
bob.circle(10)
bob.end_fill()
bob.color("black")
bob.goto(-55,-5)
bob.color("blue")
bob.write("B", font=("Arial", 5, "normal"))
bob.color("Black")
bob.penup()
bob.goto(-20,30)
bob.begin_fill()
bob.fillcolor(164, 24, 62)
bob.circle(10)
bob.end_fill()
bob.color("black")
bob.penup()
bob.goto(-25,15)
bob.color("blue")
bob.write("A", font=("Arial", 5, "normal"))
bob.color("black")
bob.penup()

#screen and logo for gameboy
bob.goto(-150,140)
bob.seth(0)
bob.pendown()
bob.forward(150)
bob.penup()
bob.goto(-140,130)
bob.pendown()
bob.begin_fill()
bob.fillcolor(147, 143, 146)
bob.forward(130)
bob.right(90)
bob.forward(70)
bob.right(90)
bob.forward(130)
bob.right(90)
bob.forward(70)
bob.end_fill()
bob.penup()
bob.goto(-135,125)
bob.seth(0)
bob.pencolor("red")
bob.pendown()
bob.forward(30)
bob.penup()
bob.goto(-135,120)
bob.pencolor("blue")
bob.pendown()
bob.forward(30)
bob.penup()
bob.forward(1)
bob.color("white")
bob.write("DOT MATRIX WITH STEREO SOUND", font =("Arial", 3,"normal"))
bob.penup()
bob.color("black")
bob.goto(-30,125)
bob.pendown()
bob.pencolor("red")
bob.forward(18)
bob.penup()
bob.goto(-30,120)
bob.pendown()
bob.pencolor("blue")
bob.forward(18)
bob.penup()
bob.pencolor("black")
bob.color("black")
bob.seth(90)
bob.goto(-135,43)
bob.color("blue")
bob.write("Nintendo GAME BOY™", font =("Helvetica", 6,"normal"))
bob.penup()
bob.pencolor("black")
bob.color("black")
bob.goto(-130,90)
bob.begin_fill()
bob.fillcolor("red")
bob.circle(3)
bob.end_fill()
bob.penup()
bob.forward(6)
bob.left(90)
bob.forward(8)
bob.pencolor("black")
bob.color("black")
bob.write("BATTERY", font =("Helvetica", 3,"normal"))
bob.penup()
bob.seth(90)
bob.goto(-100,65)
bob.pendown()
bob.begin_fill()
bob.fillcolor(125, 159, 83)
bob.forward(50)
bob.right(90)
bob.forward(80)
bob.right(90)
bob.forward(50)
bob.right(90)
bob.forward(80)
bob.end_fill()

#could not add image to the game boy so instead put game over
bob.penup()
bob.seth(90)
bob.goto(-95,85)
bob.pendown()
bob.color("black")
bob.pencolor("black")
bob.write("GAME OVER", font =("Helvetica", 9,"normal"))
bob.hideturtle()
